# Default values for pinpoint.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
pinpoint-collector:
  replicaCount: 1

###################################
# Zookeeper - External Zookeeper
###################################
  externalZookeeperAddress: 

###################################
# Hbase - External Hbase
###################################
  externalHbaseAddress:

hbase:
  enabled: false